name: lab_todo
description: "A new Flutter project."

version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.3.0
  firebase_core: ^3.4.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true